version: "3.9"

services:
  ingestion-service:
    build: ./ingestion-service
    container_name: ingestion-service
    ports:
      - "4001:4001"
    env_file:
      - ./ingestion-service/.env
    depends_on:
      - postgres
      - redis
    networks:
      - log-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4002:4002"
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres
    networks:
      - log-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: log_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - log-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - log-network
  

  log-processor-service:
    build: ./log-processor-service
    container_name: log-processor-service
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/log_analytics
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_STREAM: logs-stream
      CONSUMER_GROUP: log-processors
      CONSUMER_NAME: processor-1
    depends_on:
      - postgres
      - redis
    networks:
    - log-network
  

volumes:
  postgres_data:
  redis_data:

networks:
  log-network:
    driver: bridge
